[colors.bright]
black = "#717C7C"
blue = "#8BA4B0"
cyan = "#7AA89F"
green = "#87A987"
magenta = "#A292A3"
red = "#E46876"
white = "#F2F1EF"
yellow = "#E6C384"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#090E13"
blue = "#658594"
cyan = "#6A9589"
green = "#8A9A7B"
magenta = "#8992A7"
red = "#C34043"
white = "#909398"
yellow = "#C4B28A"

[colors.normal]
black = "#1C1E25"
blue = "#7FB4CA"
cyan = "#8EA4A2"
green = "#98BB6C"
magenta = "#938AA9"
red = "#C34043"
white = "#C5C9C7"
yellow = "#DCA561"

[colors.primary]
background = "#090E13"
bright_foreground = "#F2F1EF"
dim_foreground = "#909398"
foreground = "#C5C9C7"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
blinking = "On"

[font]
size = 17.0

[font.normal]
family = "Iosevka Term"
style = "Medium"
# style = "Medium Extended"
# family = "JetBrainsMono Nerd Font"
# style = "SemiBold"

[font.offset]
x = 0
y = 8

[font.glyph_offset]
x = 0
y = 4

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 10
y = 0

[terminal]
