# Reference: https://github.com/i3/i3/blob/next/etc/config

config-version = 2
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
# enable-normalization-flatten-containers = false
# enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Start AeroSpace at login
start-at-login = true

[mode.main.binding]
    cmd-h = 'focus left'
    cmd-j = 'focus down'
    cmd-k = 'focus up'
    cmd-l = 'focus right'

    cmd-alt-h = 'join-with left'
    cmd-alt-j = 'join-with down'
    cmd-alt-k = 'join-with up'
    cmd-alt-l = 'join-with right'

    cmd-shift-m = 'fullscreen'
    alt-shift-r = 'balance-sizes'

    cmd-ctrl-shift-h = 'swap left'
    cmd-ctrl-shift-j = 'swap down'
    cmd-ctrl-shift-k = 'swap up'
    cmd-ctrl-shift-l = 'swap right'

    alt-r = 'mode resize'

    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'

    ctrl-alt-h = 'focus-monitor left'
    ctrl-alt-j = 'focus-monitor down'
    ctrl-alt-k = 'focus-monitor up'
    ctrl-alt-l = 'focus-monitor right'

    alt-shift-h = 'move-node-to-monitor --focus-follows-window left'
    alt-shift-j = 'move-node-to-monitor --focus-follows-window down'
    alt-shift-k = 'move-node-to-monitor --focus-follows-window up'
    alt-shift-l = 'move-node-to-monitor --focus-follows-window right'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'

    cmd-ctrl-1 = 'move-node-to-workspace 1'
    cmd-ctrl-2 = 'move-node-to-workspace 2'
    cmd-ctrl-3 = 'move-node-to-workspace 3'
    cmd-ctrl-4 = 'move-node-to-workspace 4'
    cmd-ctrl-5 = 'move-node-to-workspace 5'
    cmd-ctrl-6 = 'move-node-to-workspace 6'
    cmd-ctrl-7 = 'move-node-to-workspace 7'
    cmd-ctrl-8 = 'move-node-to-workspace 8'
    cmd-ctrl-9 = 'move-node-to-workspace 9'
    cmd-ctrl-0 = 'move-node-to-workspace 10'

    alt-shift-c = 'reload-config'

[mode.resize.binding]
    h = 'resize width -100'
    j = 'resize height +100'
    k = 'resize height -100'
    l = 'resize width +100'
    enter = 'mode main'
    esc = 'mode main'
    alt-r = 'mode main'

[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = 'main'
    5 = 'main'
    6 = 'main'
    7 = 'main'
    8 = 'main'
    9 = 'main'
    10 = 'secondary'
